create temporary table dupli
SELECT f.CHAPA as CHAPA, CODAVALIACAO, CODPARTICIPANTE, NOME, CODPESSOA, CHAPAAVALIADOR, COUNT(1) AS CONTADOR FROM participantes AS p
inner join funcionarios as f
on p.CHAPAAVALIADO = f.CHAPA and p.CODCOLIGADA = f.CODCOLIGADA
where CODAVALIACAO > 24
GROUP BY CODPESSOA, CODAVALIACAO
HAVING CONTADOR > 1;

SELECT f.CHAPA as CHAPA, f.CODSITUACAO AS SITUACAO,  p.CODAVALIACAO, p.CODPARTICIPANTE, d.NOME, d.CODPESSOA, p.CHAPAAVALIADOR, 
LID.NOME, n.NOTAAVALIADOR FROM participantes AS p
inner join funcionarios as f
on p.CHAPAAVALIADO = f.CHAPA and p.CODCOLIGADA = f.CODCOLIGADA
INNER join dupli as d on d.CODPESSOA = f.CODPESSOA AND p.CODAVALIACAO = d.CODAVALIACAO
LEFT JOIN notas AS n on n.CODAVALIACAO = p.CODAVALIACAO and n.CODCOLIGADA = p.CODCOLIGADA and n.CODPARTICIPANTE = p.CODPARTICIPANTE
LEFT JOIN funcionarios as LID on LID.CHAPA = p.CHAPAAVALIADOR
where p.CODAVALIACAO > 24 
group by p.CODPARTICIPANTE
having d.NOME IS NOT NULL
order by d.NOME, d.CODAVALIACAO
